customhost = "employee.cueoqeh1xxtj.us-east-1.rds.amazonaws.com"
customuser = "geeyong"
custompass = "Taygeeyong1214"
customdb = "employee"
custombucket = "taygeeyong-employee"
customregion = "us-east-1"
